### ISSUE TITLE
Installable through Composer.json

### ISSUE THREAD

**Issue by brunogaspar** [astockwell/countries-and-provinces-states-regions#8]
Hey @astockwell, thanks for the work on this, really awesome to have a nice usable list.

Is there any chance you can list this on Packagist.org by using [Composer](https://getcomposer.org/)?

Thanks!

**Comment by astockwell** [comment]
Hi @brunogaspar, glad you found it useful :).

I'm not terribly familiar with Composer, would the repo be usable/valuable if listed there as-is?

Also I would suppose there'd be some sort of composer.json file to add to the repo, would you be up for sending one as pull request?

**Comment by brunogaspar** [comment]
@astockwell thanks for the reply.

Sure i can get a PR rolling for this :+1: and help you out with setting it up on Packagist.org.

The idea is that, imagine that you push some updates (would be awesome if those updates would be tagged, not a requirement, but it's always nice to have stuff tagged and proper versioned) then on my end i would just run `composer update` and i get your changes easily instead of coming on GitHub, download the files and update them manually.

---

It's a bit off topic, but do you plan on add more data to the countries? Like currencies, etc..
I'm asking because there are a couple of lists available out there, with composer, like this one https://github.com/mledoze/countries but it doesn't include the provinces like yours do.

Just food for thought. Will look into the PR as soon as i've a bit of free time.
